### PR TITLE
Updated typescript dependency

### PR DESCRIPTION
**Pull request by vasek17**
Did not work with current typescript 1.5.0-beta.

### CODE REVIEW

**Comment by jbrantly** [comment]
Really? This has worked fine for me so far in all of my various tests. "~1.5.0" was enough to pull "1.5.0-beta".

**Comment by vasek17** [comment]
Getting npm ERR ETARGET
No compatible version found: typescript@'>=1.5.0 <1.6.0'

**Comment by jbrantly** [comment]
What version of NPM are you using so I can compare to what I'm using. Going to go ahead and merge though because I'd rather it work for everyone.

**Comment by vasek17** [comment]
I am using npm 2.7.5. 
If I mark my app version (where listing ts-loader as a dependency) as beta, it works fine for me with ~1.5.0. But if the version is stable, tilde operator does not consider prereleases.

**Comment by jbrantly** [comment]
Ah, good to know. Thanks!

**Comment by jbrantly** [comment]
Published in v0.4.2. Thanks again!

**Pull request merged**
